# Generated by Django 2.2.4 on 2019-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lixo_eletronico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceiro', models.CharField(max_length=200, null=True, verbose_name='Parceiro')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
            ],
        ),
    ]
