# Generated by Django 2.2.4 on 2019-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lixo_eletronico', '0002_parcerias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='localizacao',
            field=models.CharField(max_length=500, verbose_name='Endereço do Evento'),
        ),
    ]
