# Generated by Django 2.2.4 on 2019-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lixo_eletronico', '0003_auto_20190826_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/images/eventos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='parcerias',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/images/parcerias/', verbose_name='Logo'),
        ),
    ]
