# Generated by Django 2.2.4 on 2019-08-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lixo_eletronico', '0004_auto_20190826_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagens',
            old_name='evento',
            new_name='evento_realizado',
        ),
    ]
