# Generated by Django 2.2.4 on 2019-08-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lixo_eletronico', '0005_auto_20190828_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosrealizados',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizados', to='lixo_eletronico.Eventos'),
        ),
    ]
